
-- IN THIS PART I USED SNOWFLAKE TO CREATE VITUAL WAREHOUSE, I CREATE SOME USERS AND CUSTOM ROLES AND CREATE THE DESTINATION TABLES FOR THE ETL SYSTEM 

-- USE SNOWFLAKE DEFAULT WAREHOUSE FOR OPERATIONS 
USE WAREHOUSE COMPUTE_WH;
USE ROLE SECURITYADMIN;

-- CREATE THE 3 ROLES 
CREATE ROLE PROJECT_MANAGER;
CREATE ROLE DATA_ENGINEER;
CREATE ROLE ANALYST;

-- GRANT DEFAULT ROLES TO THE 3 CUSTOM ROLES 
USE ROLE SECURITYADMIN;
GRANT ROLE PROJECT_MANAGER TO ROLE SECURITYADMIN;
SHOW GRANTS TO ROLE SECURITYADMIN;

-- GRANT CUSTOM ROLE TO ANOTHER CUSTOM ROLE 
GRANT ROLE DATA_ENGINEER TO ROLE PROJECT_MANAGER;
GRANT ROLE ANALYST TO ROLE PROJECT_MANAGER;
SHOW GRANTS TO ROLE PROJECT_MANAGER;

-- CREATE THE 3 USERS USING USER ADMIN ROLE
USE ROLE USERADMIN;
CREATE USER PROJECT_MANAGER_01 PASSWORD='HELLOWORLD@12345' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER DATA_ENGINEER_01 PASSWORD='HELLOWORLD@12345' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER ANALYST_01 PASSWORD='HELLOWORLD@12345' MUST_CHANGE_PASSWORD=FALSE;

-- GRANT THE 3 CUSTOM ROLES TO THE 3 NEW USERS USING SECURITY ADMIN ROLE 
USE ROLE SECURITYADMIN;
GRANT ROLE PROJECT_MANAGER TO USER PROJECT_MANAGER_01;
GRANT ROLE DATA_ENGINEER TO USER DATA_ENGINEER_01;
GRANT ROLE ANALYST TO USER ANALYST_01;

-- SET THE NEW ROLES AS A DEFAULT ROLE 
ALTER USER PROJECT_MANAGER_01 SET DEFAULT_ROLE='PROJECT_MANAGER';
ALTER USER DATA_ENGINEER_01 SET DEFAULT_ROLE='DATA_ENGINEER';
ALTER USER ANALYST_01 SET DEFAULT_ROLE='ANALYST';

-- ALLOW THE ROLE PROJECT MANAGER TO CREATE 
USE ROLE SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE PROJECT_MANAGER;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE PROJECT_MANAGER;

-- SET ROLE PUBLIC AS A DEFAULT ROLE FOR 3 NEW USERS
USE ROLE SECURITYADMIN;
ALTER USER PROJECT_MANAGER_01 SET DEFAULT_ROLE='PUBLIC';
ALTER USER DATA_ENGINEER_01 SET DEFAULT_ROLE='PUBLIC';
ALTER USER ANALYST_01 SET DEFAULT_ROLE='PUBLIC';

-- ALLOW ROLE DATA ENGINEER TO CREATE TASKS
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_ENGINEER;

-- ASSIGN ROLE ACCOUNT ADMIN TO ROLE DATA ENGINEER 
GRANT ROLE ACCOUNTADMIN TO USER DATA_ENGINEER_01;


-- NOTE: THE FOLLOWING SQL STATEMENTS WERE WRITTEN USING THE USER PROJECT_MANAGER_01

-- USE ROLE PROJECT MANAGER 
USE ROLE PROJECT_MANAGER;

-- CREATE A VIRTUAL WAREHOUSE "ADHOC_WH" WITH THE FOLLOWING PARAMETERS
CREATE WAREHOUSE ADHOC_WH
WAREHOUSE_SIZE=XSMALL
MAX_CLUSTER_COUNT=2
MIN_CLUSTER_COUNT=1
SCALING_POLICY=STANDARD
AUTO_SUSPEND=600
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;

-- CREATE DATABASE "ENTERPRISE_DB" FOR DESTINATION TABLES 
USE WAREHOUSE ADHOC_WH;
CREATE DATABASE ENTERPRISE_DB;

-- CREATE 2 SCHEMA "DEV_ENVR" AND "PROD_ENVR"
USE DATABASE ENTERPRISE_DB;
CREATE SCHEMA DEV_ENVR;
CREATE SCHEMA PROD_ENVR;

-- CREATE 2 TABLES "CUSTOMER_DETAILS_TABLE" & "SALES_DETAILS_TABLE" WITH THE SAME STRUCTURE OF THE DATA FILES 
USE SCHEMA DEV_ENVR;
CREATE TABLE CUSTOMER_DETAILS_TABLE
(
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
ADDRESS VARCHAR(50),
CITY VARCHAR(50),
COUNTRY VARCHAR(50),
STATE VARCHAR(50),
PHONE_1 VARCHAR(50),
PHONE_2 VARCHAR(50),
EMAIL VARCHAR(50),
INVOICE_ID VARCHAR(50),
CUSTOMER_TYPE VARCHAR(50),
PRODUCT_LINE VARCHAR(50),
RATING FLOAT
);

CREATE TABLE SALES_DETAILS_TABLE
(
ROW_ID INT,
ORDER_ID VARCHAR(50),
ORDER_DATE DATE,
SHIP_DATE DATE,
SHIP_MODE VARCHAR(50),
CUSTOMER_ID VARCHAR(50),
CUSTOMER_NAME VARCHAR(50),
SEGMENT VARCHAR(50),
COUNTRY VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
POSTAL_CODE BIGINT,
REGION VARCHAR(50),
PRODUCT_ID VARCHAR(50),
CETEGORY VARCHAR(50),
SUB_CATEGORY VARCHAR(50),
PRODUCT_NAME VARCHAR(50),
SALES FLOAT,
QUANTITY INT,
DISCOUNT FLOAT,
PROFIT FLOAT
);



