
-- PART-2: IN THIS PART I CREATE A FILE FORMAT AND STAGE FOR THE DATA LOADING AND ASSIGN SOME PRIVILEGES TO CUSTOM ROLES "DATA_ENGINEER" & "ANALYST"

-- NOTE: THE FOLLOWING CODE STATEMENTS WERE WRITTEN USING THE USER PROJECT MANAGER 

-- CREATING FILE FORMAT FOR THE DATA
USE ENTERPRISE_DB;
USE SCHEMA DEV_ENVR;
CREATE FILE FORMAT CSV_FF
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = NONE
ESCAPE_UNENCLOSED_FIELD = '/';

-- CREATE AN INTERNAL STAGE TO LOAD THE DATA FROM THE LOCAL MACHINE
CREATE OR REPLACE STAGE INT_STAGE
FILE_FORMAT = CSV_FF;

-- PUT THE DATA INTO STAGE TO DELIVER IT TO THE TABLES USING WIZARD
-- I USED SNOWFLAKE UI TO LOAD THE DATA INSTEAD OF SNOW CLI 

-- CHECK THE DATA IN TABLES
SELECT * FROM CUSTOMER_DETAILS_TABLE ;
SELECT * FROM SALES_DETAILS_TABLE;

-- GRANT PRIVILEGES TO CUSTOM ROLES

-- DATA ENGINEER PRIVILEGES
GRANT USAGE ON WAREHOUSE ADHOC_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE ENTERPRISE_DB TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA DEV_ENVR TO ROLE DATA_ENGINEER;
GRANT ALL ON ALL TABLES IN SCHEMA DEV_ENVR TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA PROD_ENVR TO ROLE DATA_ENGINEER;
GRANT ALL ON ALL TABLES IN SCHEMA PROD_ENVR TO ROLE DATA_ENGINEER;

-- ANALYST PRIVILEGES
GRANT USAGE ON WAREHOUSE ADHOC_WH TO ROLE ANALYST;
GRANT USAGE ON DATABASE ENTERPRISE_DB TO ROLE ANALYST;
GRANT ALL ON SCHEMA PROD_ENVR TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD_ENVR TO ROLE ANALYST;


